import psycopg2
import json

conn = psycopg2.connect(
    host='localhost',
    database='demo',
    user='postgres',
    password='admin'
)
cur = conn.cursor()

jobs_data = [
    {'job_id': 'xa001', 'job_name': 'Python高级开发工程师', 'company_name': '三星电子', 'salary_range': '20K-35K', 'salary_min': 20000, 'salary_max': 35000, 'city': '西安', 'district': '高新区', 'experience': '3-5年', 'education': '本科', 'company_scale': '10000人以上', 'company_industry': '电子信息', 'finance_stage': '上市公司', 'job_benefits': ['五险一金', '年终奖金', '定期体检', '带薪年假'], 'posted_time': '今天发布', 'job_detail_url': 'https://www.zhipin.com/job_detail/xa001.html'},
    {'job_id': 'xa002', 'job_name': 'Java后端开发', 'company_name': '华为技术有限公司', 'salary_range': '18K-30K', 'salary_min': 18000, 'salary_max': 30000, 'city': '西安', 'district': '高新区', 'experience': '2-5年', 'education': '本科', 'company_scale': '10000人以上', 'company_industry': '通信设备', 'finance_stage': '上市公司', 'job_benefits': ['六险一金', '餐补', '交通补贴'], 'posted_time': '1天前发布', 'job_detail_url': 'https://www.zhipin.com/job_detail/xa002.html'},
    {'job_id': 'xa003', 'job_name': '前端开发工程师', 'company_name': '中兴通讯', 'salary_range': '15K-25K', 'salary_min': 15000, 'salary_max': 25000, 'city': '西安', 'district': '雁塔区', 'experience': '1-3年', 'education': '本科', 'company_scale': '10000人以上', 'company_industry': '通信设备', 'finance_stage': '上市公司', 'job_benefits': ['五险一金', '绩效奖金', '节日福利'], 'posted_time': '2天前发布', 'job_detail_url': 'https://www.zhipin.com/job_detail/xa003.html'},
    {'job_id': 'xa004', 'job_name': '数据工程师', 'company_name': '英特尔半导体', 'salary_range': '22K-38K', 'salary_min': 22000, 'salary_max': 38000, 'city': '西安', 'district': '高新区', 'experience': '3-5年', 'education': '硕士', 'company_scale': '10000人以上', 'company_industry': '半导体', 'finance_stage': '上市公司', 'job_benefits': ['年终奖金', '股票期权', '技术培训'], 'posted_time': '今天发布', 'job_detail_url': 'https://www.zhipin.com/job_detail/xa004.html'},
    {'job_id': 'xa005', 'job_name': '算法工程师', 'company_name': '谷歌中国', 'salary_range': '30K-50K', 'salary_min': 30000, 'salary_max': 50000, 'city': '西安', 'district': '高新区', 'experience': '3-5年', 'education': '硕士', 'company_scale': '1000-9999人', 'company_industry': '互联网', 'finance_stage': '上市公司', 'job_benefits': ['免费三餐', '健身房', '股票期权'], 'posted_time': '3天前发布', 'job_detail_url': 'https://www.zhipin.com/job_detail/xa005.html'},
    {'job_id': 'xa006', 'job_name': '全栈开发工程师', 'company_name': '思科系统', 'salary_range': '20K-35K', 'salary_min': 20000, 'salary_max': 35000, 'city': '西安', 'district': '高新区', 'experience': '2-4年', 'education': '本科', 'company_scale': '10000人以上', 'company_industry': '网络设备', 'finance_stage': '上市公司', 'job_benefits': ['弹性工作', '年度体检', '带薪年假'], 'posted_time': '今天发布', 'job_detail_url': 'https://www.zhipin.com/job_detail/xa006.html'},
    {'job_id': 'xa007', 'job_name': '测试工程师', 'company_name': '微软中国', 'salary_range': '15K-25K', 'salary_min': 15000, 'salary_max': 25000, 'city': '西安', 'district': '雁塔区', 'experience': '1-3年', 'education': '本科', 'company_scale': '1000-9999人', 'company_industry': '互联网', 'finance_stage': '上市公司', 'job_benefits': ['五险一金', '技术培训', '节日福利'], 'posted_time': '1天前发布', 'job_detail_url': 'https://www.zhipin.com/job_detail/xa007.html'},
    {'job_id': 'xa008', 'job_name': '运维工程师', 'company_name': 'IBM中国', 'salary_range': '18K-28K', 'salary_min': 18000, 'salary_max': 28000, 'city': '西安', 'district': '高新区', 'experience': '2-5年', 'education': '本科', 'company_scale': '10000人以上', 'company_industry': 'IT服务', 'finance_stage': '上市公司', 'job_benefits': ['年终奖金', '绩效奖金', '补充医疗保险'], 'posted_time': '2天前发布', 'job_detail_url': 'https://www.zhipin.com/job_detail/xa008.html'},
    {'job_id': 'xa009', 'job_name': '产品经理', 'company_name': '亚马逊中国', 'salary_range': '20K-35K', 'salary_min': 20000, 'salary_max': 35000, 'city': '西安', 'district': '高新区', 'experience': '3-5年', 'education': '本科', 'company_scale': '10000人以上', 'company_industry': '互联网', 'finance_stage': '上市公司', 'job_benefits': ['六险一金', '股票期权', '带薪年假'], 'posted_time': '今天发布', 'job_detail_url': 'https://www.zhipin.com/job_detail/xa009.html'},
    {'job_id': 'xa010', 'job_name': '机器学习工程师', 'company_name': '英伟达', 'salary_range': '28K-45K', 'salary_min': 28000, 'salary_max': 45000, 'city': '西安', 'district': '高新区', 'experience': '2-4年', 'education': '硕士', 'company_scale': '1000-9999人', 'company_industry': '人工智能', 'finance_stage': '上市公司', 'job_benefits': ['技术挑战', '国际团队', '股票期权'], 'posted_time': '1天前发布', 'job_detail_url': 'https://www.zhipin.com/job_detail/xa010.html'},
    {'job_id': 'bj001', 'job_name': 'Go开发工程师', 'company_name': '字节跳动', 'salary_range': '25K-45K', 'salary_min': 25000, 'salary_max': 45000, 'city': '北京', 'district': '海淀区', 'experience': '2-5年', 'education': '本科', 'company_scale': '10000人以上', 'company_industry': '互联网', 'finance_stage': '上市公司', 'job_benefits': ['免费三餐', '下午茶', '健身房'], 'posted_time': '今天发布', 'job_detail_url': 'https://www.zhipin.com/job_detail/bj001.html'},
    {'job_id': 'bj002', 'job_name': 'Java架构师', 'company_name': '阿里巴巴', 'salary_range': '35K-60K', 'salary_min': 35000, 'salary_max': 60000, 'city': '北京', 'district': '朝阳区', 'experience': '5-10年', 'education': '本科', 'company_scale': '10000人以上', 'company_industry': '互联网', 'finance_stage': '上市公司', 'job_benefits': ['年终奖金', '股票期权', '住房补贴'], 'posted_time': '1天前发布', 'job_detail_url': 'https://www.zhipin.com/job_detail/bj002.html'},
    {'job_id': 'bj003', 'job_name': '前端开发专家', 'company_name': '腾讯科技', 'salary_range': '28K-50K', 'salary_min': 28000, 'salary_max': 50000, 'city': '北京', 'district': '海淀区', 'experience': '3-5年', 'education': '本科', 'company_scale': '10000人以上', 'company_industry': '互联网', 'finance_stage': '上市公司', 'job_benefits': ['五险一金', '年底双薪', '节日福利'], 'posted_time': '2天前发布', 'job_detail_url': 'https://www.zhipin.com/job_detail/bj003.html'},
    {'job_id': 'bj004', 'job_name': '数据科学家', 'company_name': '百度在线', 'salary_range': '30K-55K', 'salary_min': 30000, 'salary_max': 55000, 'city': '北京', 'district': '海淀区', 'experience': '3-5年', 'education': '硕士', 'company_scale': '10000人以上', 'company_industry': '人工智能', 'finance_stage': '上市公司', 'job_benefits': ['技术培训', '论文发表支持', '弹性工作'], 'posted_time': '今天发布', 'job_detail_url': 'https://www.zhipin.com/job_detail/bj004.html'},
    {'job_id': 'bj005', 'job_name': '安全工程师', 'company_name': '360安全', 'salary_range': '22K-40K', 'salary_min': 22000, 'salary_max': 40000, 'city': '北京', 'district': '朝阳区', 'experience': '2-5年', 'education': '本科', 'company_scale': '1000-9999人', 'company_industry': '网络安全', 'finance_stage': '上市公司', 'job_benefits': ['五险一金', '安全培训', '证书补贴'], 'posted_time': '3天前发布', 'job_detail_url': 'https://www.zhipin.com/job_detail/bj005.html'},
    {'job_id': 'sh001', 'job_name': 'Rust开发工程师', 'company_name': '特斯拉', 'salary_range': '30K-50K', 'salary_min': 30000, 'salary_max': 50000, 'city': '上海', 'district': '浦东新区', 'experience': '2-4年', 'education': '本科', 'company_scale': '10000人以上', 'company_industry': '新能源汽车', 'finance_stage': '上市公司', 'job_benefits': ['股票期权', '购车补贴', '免费充电'], 'posted_time': '今天发布', 'job_detail_url': 'https://www.zhipin.com/job_detail/sh001.html'},
    {'job_id': 'sh002', 'job_name': 'iOS开发工程师', 'company_name': '苹果中国', 'salary_range': '25K-42K', 'salary_min': 25000, 'salary_max': 42000, 'city': '上海', 'district': '静安区', 'experience': '2-5年', 'education': '本科', 'company_scale': '1000-9999人', 'company_industry': '消费电子', 'finance_stage': '上市公司', 'job_benefits': ['五险一金', '年度体检', '带薪年假'], 'posted_time': '1天前发布', 'job_detail_url': 'https://www.zhipin.com/job_detail/sh002.html'},
    {'job_id': 'sh003', 'job_name': '大数据开发', 'company_name': '拼多多', 'salary_range': '28K-48K', 'salary_min': 28000, 'salary_max': 48000, 'city': '上海', 'district': '长宁区', 'experience': '3-5年', 'education': '本科', 'company_scale': '10000人以上', 'company_industry': '电商', 'finance_stage': '上市公司', 'job_benefits': ['免费班车', '餐补', '绩效奖金'], 'posted_time': '2天前发布', 'job_detail_url': 'https://www.zhipin.com/job_detail/sh003.html'},
    {'job_id': 'sh004', 'job_name': 'Android架构师', 'company_name': '美团', 'salary_range': '30K-52K', 'salary_min': 30000, 'salary_max': 52000, 'city': '上海', 'district': '浦东新区', 'experience': '4-6年', 'education': '本科', 'company_scale': '10000人以上', 'company_industry': '本地生活', 'finance_stage': '上市公司', 'job_benefits': ['年终奖金', '股票期权', '节日福利'], 'posted_time': '今天发布', 'job_detail_url': 'https://www.zhipin.com/job_detail/sh004.html'},
    {'job_id': 'sh005', 'job_name': 'NLP工程师', 'company_name': '商汤科技', 'salary_range': '32K-55K', 'salary_min': 32000, 'salary_max': 55000, 'city': '上海', 'district': '徐汇区', 'experience': '2-4年', 'education': '硕士', 'company_scale': '1000-9999人', 'company_industry': '人工智能', 'finance_stage': '上市公司', 'job_benefits': ['技术论文支持', 'GPU资源', '弹性工作'], 'posted_time': '1天前发布', 'job_detail_url': 'https://www.zhipin.com/job_detail/sh005.html'},
    {'job_id': 'sz001', 'job_name': '嵌入式开发工程师', 'company_name': '大疆创新', 'salary_range': '25K-45K', 'salary_min': 25000, 'salary_max': 45000, 'city': '深圳', 'district': '南山区', 'experience': '2-5年', 'education': '本科', 'company_scale': '1000-9999人', 'company_industry': '无人机', 'finance_stage': '上市公司', 'job_benefits': ['研发新品内购', '年度旅游', '技术培训'], 'posted_time': '今天发布', 'job_detail_url': 'https://www.zhipin.com/job_detail/sz001.html'},
    {'job_id': 'sz002', 'job_name': '音视频工程师', 'company_name': '腾讯音乐', 'salary_range': '28K-48K', 'salary_min': 28000, 'salary_max': 48000, 'city': '深圳', 'district': '南山区', 'experience': '3-5年', 'education': '本科', 'company_scale': '1000-9999人', 'company_industry': '在线音乐', 'finance_stage': '上市公司', 'job_benefits': ['音乐节门票', '健身补贴', '年终奖金'], 'posted_time': '1天前发布', 'job_detail_url': 'https://www.zhipin.com/job_detail/sz002.html'},
    {'job_id': 'sz003', 'job_name': '区块链开发', 'company_name': '华为区块链', 'salary_range': '30K-52K', 'salary_min': 30000, 'salary_max': 52000, 'city': '深圳', 'district': '龙岗区', 'experience': '2-4年', 'education': '本科', 'company_scale': '10000人以上', 'company_industry': '区块链', 'finance_stage': '上市公司', 'job_benefits': ['技术研究', '专利奖励', '五险一金'], 'posted_time': '2天前发布', 'job_detail_url': 'https://www.zhipin.com/job_detail/sz003.html'},
    {'job_id': 'sz004', 'job_name': 'GPU优化工程师', 'company_name': '比亚迪', 'salary_range': '25K-42K', 'salary_min': 25000, 'salary_max': 42000, 'city': '深圳', 'district': '坪山区', 'experience': '2-5年', 'education': '硕士', 'company_scale': '10000人以上', 'company_industry': '新能源汽车', 'finance_stage': '上市公司', 'job_benefits': ['购车优惠', '员工宿舍', '年终奖金'], 'posted_time': '今天发布', 'job_detail_url': 'https://www.zhipin.com/job_detail/sz004.html'},
    {'job_id': 'sz005', 'job_name': '游戏服务端开发', 'company_name': '网易游戏', 'salary_range': '28K-50K', 'salary_min': 28000, 'salary_max': 50000, 'city': '深圳', 'district': '南山区', 'experience': '3-5年', 'education': '本科', 'company_scale': '10000人以上', 'company_industry': '游戏', 'finance_stage': '上市公司', 'job_benefits': ['游戏内测资格', '年终奖', '带薪年假'], 'posted_time': '3天前发布', 'job_detail_url': 'https://www.zhipin.com/job_detail/sz005.html'},
    {'job_id': 'hz001', 'job_name': '云计算工程师', 'company_name': '阿里云', 'salary_range': '25K-45K', 'salary_min': 25000, 'salary_max': 45000, 'city': '杭州', 'district': '西湖区', 'experience': '2-5年', 'education': '本科', 'company_scale': '10000人以上', 'company_industry': '云计算', 'finance_stage': '上市公司', 'job_benefits': ['云资源免费', '技术认证', '年度体检'], 'posted_time': '今天发布', 'job_detail_url': 'https://www.zhipin.com/job_detail/hz001.html'},
    {'job_id': 'hz002', 'job_name': '电商架构师', 'company_name': '蚂蚁集团', 'salary_range': '35K-60K', 'salary_min': 35000, 'salary_max': 60000, 'city': '杭州', 'district': '西湖区', 'experience': '5-8年', 'education': '本科', 'company_scale': '10000人以上', 'company_industry': '金融科技', 'finance_stage': '上市公司', 'job_benefits': ['股票期权', '年终奖金', '补充公积金'], 'posted_time': '1天前发布', 'job_detail_url': 'https://www.zhipin.com/job_detail/hz002.html'},
    {'job_id': 'hz003', 'job_name': '推荐算法工程师', 'company_name': '抖音', 'salary_range': '32K-55K', 'salary_min': 32000, 'salary_max': 55000, 'city': '杭州', 'district': '余杭区', 'experience': '2-4年', 'education': '硕士', 'company_scale': '10000人以上', 'company_industry': '短视频', 'finance_stage': '上市公司', 'job_benefits': ['流量扶持', '论文发表', '弹性工作'], 'posted_time': '2天前发布', 'job_detail_url': 'https://www.zhipin.com/job_detail/hz003.html'},
    {'job_id': 'xa011', 'job_name': 'DevOps工程师', 'company_name': '思爱普西安', 'salary_range': '18K-30K', 'salary_min': 18000, 'salary_max': 30000, 'city': '西安', 'district': '高新区', 'experience': '2-5年', 'education': '本科', 'company_scale': '1000-9999人', 'company_industry': '企业服务', 'finance_stage': '上市公司', 'job_benefits': ['五险一金', '年度体检', '弹性工作'], 'posted_time': '今天发布', 'job_detail_url': 'https://www.zhipin.com/job_detail/xa011.html'},
    {'job_id': 'xa012', 'job_name': '数据库工程师', 'company_name': '甲骨文西安', 'salary_range': '20K-35K', 'salary_min': 20000, 'salary_max': 35000, 'city': '西安', 'district': '高新区', 'experience': '3-5年', 'education': '本科', 'company_scale': '10000人以上', 'company_industry': '数据库软件', 'finance_stage': '上市公司', 'job_benefits': ['股票期权', '技术培训', '带薪年假'], 'posted_time': '1天前发布', 'job_detail_url': 'https://www.zhipin.com/job_detail/xa012.html'},
    {'job_id': 'xa013', 'job_name': '网络安全工程师', 'company_name': '华为西安研究所', 'salary_range': '22K-38K', 'salary_min': 22000, 'salary_max': 38000, 'city': '西安', 'district': '高新区', 'experience': '2-5年', 'education': '本科', 'company_scale': '10000人以上', 'company_industry': '网络安全', 'finance_stage': '上市公司', 'job_benefits': ['六险一金', '餐补', '交通补贴'], 'posted_time': '今天发布', 'job_detail_url': 'https://www.zhipin.com/job_detail/xa013.html'},
    {'job_id': 'xa014', 'job_name': 'C++开发工程师', 'company_name': '腾讯西安', 'salary_range': '20K-35K', 'salary_min': 20000, 'salary_max': 35000, 'city': '西安', 'district': '雁塔区', 'experience': '2-4年', 'education': '本科', 'company_scale': '10000人以上', 'company_industry': '互联网', 'finance_stage': '上市公司', 'job_benefits': ['五险一金', '年终奖金', '节日福利'], 'posted_time': '2天前发布', 'job_detail_url': 'https://www.zhipin.com/job_detail/xa014.html'},
    {'job_id': 'xa015', 'job_name': 'PHP开发工程师', 'company_name': '百度西安', 'salary_range': '15K-25K', 'salary_min': 15000, 'salary_max': 25000, 'city': '西安', 'district': '高新区', 'experience': '1-3年', 'education': '本科', 'company_scale': '10000人以上', 'company_industry': '互联网', 'finance_stage': '上市公司', 'job_benefits': ['免费班车', '餐补', '绩效奖金'], 'posted_time': '3天前发布', 'job_detail_url': 'https://www.zhipin.com/job_detail/xa015.html'},
    {'job_id': 'xa016', 'job_name': 'UI设计师', 'company_name': '阿里巴巴西安', 'salary_range': '15K-28K', 'salary_min': 15000, 'salary_max': 28000, 'city': '西安', 'district': '高新区', 'experience': '2-4年', 'education': '本科', 'company_scale': '10000人以上', 'company_industry': '互联网', 'finance_stage': '上市公司', 'job_benefits': ['五险一金', '年度旅游', '节日福利'], 'posted_time': '今天发布', 'job_detail_url': 'https://www.zhipin.com/job_detail/xa016.html'},
    {'job_id': 'xa017', 'job_name': '项目经理', 'company_name': '中兴西安', 'salary_range': '18K-32K', 'salary_min': 18000, 'salary_max': 32000, 'city': '西安', 'district': '雁塔区', 'experience': '3-5年', 'education': '本科', 'company_scale': '10000人以上', 'company_industry': '通信设备', 'finance_stage': '上市公司', 'job_benefits': ['年终奖金', '股票期权', '带薪年假'], 'posted_time': '1天前发布', 'job_detail_url': 'https://www.zhipin.com/job_detail/xa017.html'},
    {'job_id': 'xa018', 'job_name': '数据分析师', 'company_name': '亚马逊西安', 'salary_range': '18K-30K', 'salary_min': 18000, 'salary_max': 30000, 'city': '西安', 'district': '高新区', 'experience': '2-4年', 'education': '本科', 'company_scale': '10000人以上', 'company_industry': '互联网', 'finance_stage': '上市公司', 'job_benefits': ['六险一金', '技术培训', '弹性工作'], 'posted_time': '2天前发布', 'job_detail_url': 'https://www.zhipin.com/job_detail/xa018.html'},
    {'job_id': 'xa019', 'job_name': '技术架构师', 'company_name': '谷歌西安', 'salary_range': '40K-65K', 'salary_min': 40000, 'salary_max': 65000, 'city': '西安', 'district': '高新区', 'experience': '5-8年', 'education': '硕士', 'company_scale': '1000-9999人', 'company_industry': '互联网', 'finance_stage': '上市公司', 'job_benefits': ['股票期权', '免费三餐', '健身房'], 'posted_time': '今天发布', 'job_detail_url': 'https://www.zhipin.com/job_detail/xa019.html'},
    {'job_id': 'xa020', 'job_name': '深度学习工程师', 'company_name': '英伟达西安', 'salary_range': '30K-50K', 'salary_min': 30000, 'salary_max': 50000, 'city': '西安', 'district': '高新区', 'experience': '2-4年', 'education': '硕士', 'company_scale': '1000-9999人', 'company_industry': '人工智能', 'finance_stage': '上市公司', 'job_benefits': ['GPU资源', '技术论文支持', '股票期权'], 'posted_time': '1天前发布', 'job_detail_url': 'https://www.zhipin.com/job_detail/xa020.html'},
]

count = 0
for job in jobs_data:
    try:
        benefits_json = json.dumps(job['job_benefits'], ensure_ascii=False)
        cur.execute('''
            INSERT INTO jobs (
                job_id, job_name, company_name, salary_range, salary_min, salary_max,
                city, district, experience, education,
                company_scale, company_industry, finance_stage,
                job_benefits, posted_time, job_detail_url
            ) VALUES (
                %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s
            )
            ON CONFLICT (job_id) DO NOTHING
        ''', (
            job['job_id'], job['job_name'], job['company_name'], 
            job['salary_range'], job['salary_min'], job['salary_max'],
            job['city'], job['district'], job['experience'], job['education'],
            job['company_scale'], job['company_industry'], job['finance_stage'],
            benefits_json, job['posted_time'], job['job_detail_url']
        ))
        count += 1
    except Exception as e:
        print(f'插入失败 {job["job_id"]}: {e}')

conn.commit()
cur.close()
conn.close()
print(f'成功插入 {count} 条测试数据')
